name: FPL Assistant Backend CI

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      FLASK_APP: app.main
      DB_HOST: localhost:4000
      DB_USERNAME: fpltest
      DB_PASS: testpass

    services:
      mysql:
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: test
          MYSQL_DATABASE: FPL
          MYSQL_USER: ${{ env.DB_USERNAME }}
          MYSQL_PASSWORD: ${{ env.DB_PASS }}
        ports:
          - 4000:3306
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Initialize testing DB
        run: flask initdb -t
      - name: Run tests with pytest
        run: python -m pytest 

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - uses: actions/checkout@v2

    - name: Build Container
      run: docker build -t strangeloop1710/fpl-api:pr-latest .

    - name: Push Container
      run: docker push strangeloop1710/fpl-api:pr-latest
