name: FPL Assistant Deployment

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger Deployment
      run: |
        curl -X POST https://api.github.com/repos/Anirudh-C/fpl-assistant-react/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ACCESS_TOKEN }} \
          --data '{"event_type": "init-deploy"}'
